# -------------------------------------------------------------------------
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/config.yaml
# -------------------------------------------------------------------------
config:
  install_tree:
    padded_length: 128

