# -------------------------------------------------------------------------
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/config.yaml
# -------------------------------------------------------------------------
config:
  install_tree:
    padded_length: 128
  misc_cache: $spack/../misc_cache
  test_stage: $spack/../test_stage
  build_stage:
    - $spack/../build_stage
repos:
  builtin:
    destination: $spack/../packages
